zsh configuration using antigen

diff --git a/home/zshrc b/home/zshrc
--- a/home/zshrc
+++ b/home/zshrc
@@ -1,68 +1,68 @@
-# If you come from bash you might have to change your $PATH.
-# export PATH=$HOME/bin:/usr/local/bin:$PATH
+# Enable profiling
+# zmodload zsh/zprof
 
-# Path to your oh-my-zsh installation.
-export ZSH=$HOME/.oh-my-zsh
+# If you don't have antigen installed, you're probably running on a new
+# machine
+if [[ ! -f /usr/local/share/antigen/antigen.zsh ]]; then
+  # Install antigen on Mac OS
+  if [[ "$OSTYPE" == "darwin"* ]]; then
+    if ! type "$brew" > /dev/null; then
+      echo '`brew` is missing. Installing...'
+      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+    fi
+    echo 'Installing `antigen` for .zshrc plugin management...'
+    brew install antigen
+  else
+    echo '.zshrc requires `antigen` for plugin management! Please install it.'
+    return 1
+  fi
+fi
 
-# Set name of the theme to load. Optionally, if you set this to "random"
-# it'll load a random theme each time that oh-my-zsh is loaded.
-# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
-ZSH_THEME="pygmalion"
+# Source anitgen for zsh plugin management
+source /usr/local/share/antigen/antigen.zsh
 
-# Uncomment the following line to use case-sensitive completion.
-# CASE_SENSITIVE="true"
+# Autocompletion w/ once-a-day loading
+autoload -Uz compinit
+typeset -i updated_at=$(date +'%j' -r ~/.zcompdump 2>/dev/null || stat -f '%Sm' -t '%j' ~/.zcompdump 2>/dev/null)
+if [ $(date +'%j') != $updated_at ]; then
+  compinit -i
+else
+  compinit -C -i
+fi
 
-# Uncomment the following line to use hyphen-insensitive completion. Case
-# sensitive completion must be off. _ and - will be interchangeable.
-# HYPHEN_INSENSITIVE="true"
+# Plugins from oh-my-zsh
+antigen bundle git
+antigen bundle vi-mode
+antigen bundle colored-man-pages
+antigen bundle autojump
+antigen bundle command-not-found
 
-# Uncomment the following line to disable bi-weekly auto-update checks.
-# DISABLE_AUTO_UPDATE="true"
+# Other plugins
+antigen bundle zsh-users/zsh-syntax-highlighting
+antigen bundle mroth/evalcache
+antigen bundle zsh-users/zsh-autosuggestions
 
-# Uncomment the following line to change how often to auto-update (in days).
-# export UPDATE_ZSH_DAYS=13
+# Theme
+antigen bundle agkozak/agkozak-zsh-prompt
+AGKOZAK_LEFT_PROMPT_ONLY=1
+AGKOZAK_PROMPT_DIRTRIM=0
+AGKOZAK_CUSTOM_SYMBOLS=(
+  '⇣⇡' # Diverged
+  '⇣' # Behind
+  '⇡' # Ahead
+  '+' # New file
+  'x' # Deleted
+  '!' # Modified
+  '>' # Renamed
+  '?' # Untracked
+  '$' # Stashed changes
+)
 
-# Uncomment the following line to disable colors in ls.
-# DISABLE_LS_COLORS="true"
+# Apply antigen configuration
+antigen apply
 
-# Uncomment the following line to disable auto-setting terminal title.
-# DISABLE_AUTO_TITLE="true"
-
-# Uncomment the following line to enable command auto-correction.
-# ENABLE_CORRECTION="true"
-
-# Uncomment the following line to display red dots whilst waiting for completion.
-# COMPLETION_WAITING_DOTS="true"
-
-# Uncomment the following line if you want to disable marking untracked files
-# under VCS as dirty. This makes repository status check for large repositories
-# much, much faster.
-# DISABLE_UNTRACKED_FILES_DIRTY="true"
-
-# Uncomment the following line if you want to change the command execution time
-# stamp shown in the history command output.
-# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
-# HIST_STAMPS="mm/dd/yyyy"
-
-# Would you like to use another custom folder than $ZSH/custom?
-# ZSH_CUSTOM=/path/to/new-custom-folder
-
-# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
-# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
-# Example format: plugins=(rails git textmate ruby lighthouse)
-# Add wisely, as too many plugins slow down shell startup.
-plugins=(git vi-mode pj zsh-syntax-highlighting colored-man-pages yarn)
-
-source $ZSH/oh-my-zsh.sh
-
-PROJECT_PATHS=(~/git)
-
-# User configuration
-
-# export MANPATH="/usr/local/man:$MANPATH"
-
-# You may need to manually set your language environment
-# export LANG=en_US.UTF-8
+# Colorize CLI ouputs
+export CLICOLOR=1
 
 # Preferred editor for local and remote sessions
 if [[ -n $SSH_CONNECTION ]]; then
@@ -71,22 +71,25 @@ else
   export EDITOR='nvim'
 fi
 
-# Compilation flags
-# export ARCHFLAGS="-arch x86_64"
+# Autocomplete settings
+unsetopt menu_complete   # do not autoselect the first completion entry
+unsetopt flowcontrol
+setopt auto_menu         # show completion menu on successive tab press
+setopt complete_in_word
+setopt always_to_end
+zstyle ':completion:*' menu select # highlight current tab selection
 
-# ssh
-# export SSH_KEY_PATH="~/.ssh/rsa_id"
+## partial completion suggestions
+zstyle ':completion:*' list-suffixes zstyle ':completion:*' expand prefix suffix 
 
-# Set personal aliases, overriding those provided by oh-my-zsh libs,
-# plugins, and themes. Aliases can be placed here, though oh-my-zsh
-# users are encouraged to define aliases within the ZSH_CUSTOM folder.
-# For a full list of active aliases, run `alias`.
-#
-# Example aliases
-# alias zshconfig="mate ~/.zshrc"
-# alias ohmyzsh="mate ~/.oh-my-zsh"
-#
-setopt HIST_IGNORE_ALL_DUPS
+# History settings
+export HISTFILE="$HOME/.zsh_history"
+export SAVEHIST=100000
+export HISTSIZE=100000
+setopt hist_ignore_all_dups
+setopt hist_reduce_blanks
+setopt inc_append_history
+setopt share_history
 
 # Extended globbing mode
 setopt extended_glob
@@ -97,34 +100,15 @@ bindkey -v
 # Reduce delay in when switching modes
 export KEYTIMEOUT=1
 
-# Change cursor size according to the mode.
-function zle-keymap-select zle-line-init
-{
-  # change cursor shape in iTerm2
-  case $KEYMAP in
-    vicmd)      print -n -- "\E]50;CursorShape=0\C-G";;  # block cursor
-    viins|main) print -n -- "\E]50;CursorShape=1\C-G";;  # line cursor
-  esac
-
-  zle reset-prompt
-  zle -R
-}
-
-function zle-line-finish
-{
-  print -n -- "\E]50;CursorShape=0\C-G"  # block cursor
-}
-
-cornell_account() {
-  git config user.name "Rachit Nigam"
-  git config user.email "rn359@cornell.edu"
-}
-
-# OPAM configuration
-. /home/rachit/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true
-
 export EDITOR=$(which nvim)
 
 [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
 
-fortune -a | cowsay | lolcat
+# Initialize pyenv
+PATH=$(pyenv root)/shims:$PATH
+_evalcache pyenv init -
+
+# Aliases
+alias cat=bat
+alias vim=nvim
+alias e=nvim
